/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  daisyui: {
    themes: [
      {
        light: {
          primary: "#3b82f6",
          "primary-content": "#f3f4f6",
          secondary: "#d1d5db",
          "secondary-content": "#111827",
          accent: "#3b82f6",
          "accent-content": "#f3f4f6",
          neutral: "#f3f4f6",
          "neutral-content": "#111827",
          "base-100": "#f3f4f6",
          "base-200": "#e5e7eb",
          "base-300": "#d1d5db",
          "base-content": "#111827",
          info: "#38bdf8",
          "info-content": "#f3f4f6",
          success: "#34d399",
          "success-content": "#f3f4f6",
          warning: "#fb923c",
          "warning-content": "#f3f4f6",
          error: "#f87171",
          "error-content": "#f3f4f6",
        },
        dark: {
          primary: "#3b82f6",
          "primary-content": "#f3f4f6",
          secondary: "#374151",
          "secondary-content": "#f3f4f6",
          accent: "#3b82f6",
          "accent-content": "#f3f4f6",
          neutral: "#111827",
          "neutral-content": "#f3f4f6",
          "base-100": "#111827",
          "base-200": "#1f2937",
          "base-300": "#374151",
          "base-content": "#f3f4f6",
          info: "#38bdf8",
          "info-content": "#f3f4f6",
          success: "#34d399",
          "success-content": "#f3f4f6",
          warning: "#fb923c",
          "warning-content": "#f3f4f6",
          error: "#f87171",
          "error-content": "#f3f4f6",
        },
      },
    ],
  },
  plugins: [require("daisyui")],
};
