name: Deploy on Commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts
        run: ssh-keyscan -H studyhero.kr >> ~/.ssh/known_hosts

      - name: Run commands on the server
        run: |
          ssh -i ~/.ssh/id_rsa studyhero@studyhero.kr "export PATH=$PATH:/home/studyhero/.nvm/versions/node/v22.9.0/bin && dploy deploy main"
